### ISSUE TITLE
Missing definition for makeExtensionsImmutable in GtfsRealtime.java

### ISSUE THREAD

**Issue by TJShen2** [MobilityData/gtfs-realtime-bindings#137]
When running the sample code provided in gtfs-realtime-bindings/java/README.md, a NoSuchMethodError occurs for the method 'void com.google.transit.realtime.GtfsRealtime$FeedMessage.makeExtensionsImmutable()'. This refers to line 201 of the mentioned file containing a call to makeExtensionsImmutable(), which is not defined anywhere.

**Comment by bdferris-v2** [comment]
I just tried this out and couldn't repro myself.

How are you running the example code?  Is `protobuf-java-3.16.1.jar` on your classpath?  That's the jar that contains the `com.google.protobuf.GeneratedMessageV3` baseclass that contains the implementation of `makeExtensionsImmutable()` so I'm wondering if it's somehow missing?  (Though you would have likely hit errors sooner I'd guess).

Do you have a stack trace you can share?  More logs?

**Comment by TJShen2** [comment]
I was using an incompatible version of protobuf-java, 4.28.2. Using version 3.16.1 this error doesn't occur. Thanks for your help.
