### ISSUE TITLE
Anyone using PHP bindings?

### ISSUE THREAD

**Issue by barbeau** [MobilityData/gtfs-realtime-bindings#46]
Is anyone in the community using the PHP bindings in https://github.com/google/gtfs-realtime-bindings-php?

I'm hitting some issues regenerating them from the gtfs-realtime.proto, as it seems proto2 files aren't officially supported by Google's protobuf compiler. More at https://github.com/google/gtfs-realtime-bindings-php/pull/4.

**Comment by weeg** [comment]
Hi! I am planning to use PHP bindings in about a month. But as I can see proto2 is not supported. Is there any workaround for this?

**Comment by barbeau** [comment]
@weeg You can use the existing legacy PHP bindings that are in the repo, but they don't have any of the new fields created after circa 2017.  I don't know of any workaround going forward for proto2 support, but I'm open to ideas if anyone else does.  Otherwise, the PHP bindings will likely be deprecated going forward until there is official support for proto2.

**Comment by ethanpooley** [comment]
We are using the PHP bindings at TransitScreen. We use this package, re-hosted from Google and using an updated protobuf version: https://packagist.org/packages/jkapron/gtfs-realtime-bindings
