### ISSUE TITLE
PLEASE update and republish the JavaScript package on NPM

### ISSUE THREAD

**Issue by ciolt** [MobilityData/gtfs-realtime-bindings#48]
[gtfs-realtime-bindings](https://www.npmjs.com/package/gtfs-realtime-bindings) is severely out of date (4 years) and the old, old version of protobuf.js is causing a lot of headaches since the current documentation doesn't reflect pbjs 2.0.5 (the package dependency published on npm)

![image](https://user-images.githubusercontent.com/5000732/56099914-62d09480-5ee1-11e9-8209-bc1ff7f92a84.png)

Please republish the newer version of the package with the updated protobuf dependency, thank you!

**Comment by ciolt** [comment]
Hey @bdferris can you re-publish the Node.js package?

**Comment by aababilov** [comment]
@bdferris does not work on realtime anymore.

Hi @anatolip-rt ! Please could you help us here?

**Comment by aababilov** [comment]
Adding @barbeau 

Hi Sean! Please could you help us here?

**Comment by ciolt** [comment]
Nevermind, I forked the source and created [`gtfs-rb`](https://www.npmjs.com/package/gtfs-rb) instead. Really nice that protobuf.js also supports creating type definitions. Works flawlessly now

I'll be maintaining it on my own, thanks

**Comment by barbeau** [comment]
@ciolt Thanks for the heads up!  Yes, we're aware of the issue and are working on a new release of this library that will be published shortly.

**Comment by michaelgosling** [comment]
@ciolt this keeps saying it cant call decode on undefined. Is there a change that needs to be made now?

**Comment by ciolt** [comment]
> @ciolt this keeps saying it cant call decode on undefined

@michaelgosling That's because `gtfs-realtime-bindings` on npm is severely out of date and uses an extremely obsolete version of protobuf.js (4+ years old)

I'm using [`gtfs-rb`](https://www.npmjs.com/package/gtfs-rb) which uses a current version of protobuf.js. Try using that instead, and open an issue on [the repo](https://github.com/cscape/gtfs-rb) if something doesn't work right

**Comment by michaelgosling** [comment]
> > @ciolt this keeps saying it cant call decode on undefined
> 
> @michaelgosling That's because `gtfs-realtime-bindings` on npm is severely out of date and uses an extremely obsolete version of protobuf.js (4+ years old)
> 
> I'm using [`gtfs-rb`](https://www.npmjs.com/package/gtfs-rb) which uses a current version of protobuf.js. Try using that instead, and open an issue on [the repo](https://github.com/cscape/gtfs-rb) if something doesn't work right

I was actually talking about gtfs-rb. I couldn't find the repo before, thanks for the link :)

**Comment by barbeau** [comment]
@ciolt and @michaelgosling I just published v0.0.5 to NPM - could you please give this a try and see if it resolves the issue?
