### ISSUE TITLE
Node.js code documentation

### ISSUE THREAD

**Issue by julianrojas87** [MobilityData/gtfs-realtime-bindings#50]
Parsing a GTFS-realtime feed is shown in the README as:
```js
var feed = GtfsRealtimeBindings.FeedMessage.decode(body);
```
But for it to work it must be:
```js
var feed = GtfsRealtimeBindings.transit_realtime.FeedMessage.decode(body);
```

**Comment by barbeau** [comment]
Thanks @julianrojas87!  I just updated the docs.

**Comment by wmcb91** [comment]
Hi @barbeau, thanks for updating the docs here! I just wanted to add that the docs on [the official Google Transit API Node.js sample](https://developers.google.com/transit/gtfs-realtime/examples/nodejs-sample) and the [NPM package page](https://www.npmjs.com/package/gtfs-realtime-bindings) have the old example with `GtfsRealtimeBindings.FeedMessage.decode(body)` as well. Please let me know if it would be helpful for me to open a new issue for this.

**Comment by barbeau** [comment]
@wmcb91 Thanks for flagging this! Yes, could you open a new issue for the Google docs? I'll re-open this issue for the NPM docs, as I believe I can edit those directly.

**Comment by barbeau** [comment]
Ok, [NPM README](https://www.npmjs.com/package/gtfs-realtime-bindings) should now be fixed. Please let me know if it doesn't look right to you.
