### ISSUE TITLE
Java - Could not find io.mobilitydata.transit:gtfs-realtime-bindings:0.0.4

### ISSUE THREAD

**Issue by AlejandroPerezArteaga** [MobilityData/gtfs-realtime-bindings#51]
I am using gradle, I have already put in my "build.gradle" the dependency: 
compile group: 'io.mobilitydata.transit', name: 'gtfs-realtime-bindings', version: '0.0.4'
but when I try to compile the project it gives me this error.

Thank´s if anyone can help me.

**Comment by barbeau** [comment]
@AlejandroPerezArteaga This is an issue on our end - we're still working with JCenter to get the latest artifacts published.

In the meantime try:

`com.google.transit:gtfs-realtime-bindings:0.0.4`

I'll update this issue when the new artifacts are available.

**Comment by barbeau** [comment]
@AlejandroPerezArteaga This issue should now be resolved - the newest release is now published under the MobilityData name space on Maven Central. Could you please try this:

~~~
<dependency>
  <groupId>io.mobilitydata.transit</groupId>
  <artifactId>gtfs-realtime-bindings</artifactId>
  <version>0.0.5</version>
</dependency>
~~~
