### ISSUE TITLE
Example Java code import statements incorrect?

### ISSUE THREAD

**Issue by nselikoff** [MobilityData/gtfs-realtime-bindings#54]
In the example Java code in [this README](https://github.com/MobilityData/gtfs-realtime-bindings/tree/master/java), the import statements use `io.mobilitydata.transit.realtime.GtfsRealtime`, but the actual path of the generated code is still `com.google.transit.realtime.GtfsRealtime`.

Since the management of the gtfs-realtime-bindings has passed to @MobilityData, will this path be updated in the generated code in the future? Or kept to maintain backwards compatibility? 

Either way a quick update to that README is needed.

**Comment by barbeau** [comment]
@nselikoff Thanks for flagging this!  Yes, this is an error in the docs - the import will remain `com.google.transit.realtime.GtfsRealtime` for backwards compatibility.  I'll fix this shortly.
