### ISSUE TITLE
I'm trying to get the current bus departure times using an API and I've used the following code... API information comes from a different company. I'm evaluating the possibility of an error in the protobuf file. Can you help?

### ISSUE THREAD

**Issue by ibrahimozden** [MobilityData/gtfs-realtime-bindings#55]
Error: invalid wire type 7 at offset 12 at BufferReader.Reader.skipType (/home/runner/node_modules/gtfs-realtime-bindings/node_modules/protobufjs/src/reader.js:375:19) at Function.decode (/home/runner/node_modules/gtfs-realtime-bindings/gtfs-realtime.js:148:28) at Request._callback (/home/runner/index.js:12:66) at Request.self.callback (/home/runner/node_modules/request/request.js:185:22) at Request.emit (events.js:198:13) at Request.EventEmitter.emit (domain.js:448:20) at Request. (/home/runner/node_modules/request/request.js:1161:10) at Request.emit (events.js:198:13) at Request.EventEmitter.emit (domain.js:448:20) at IncomingMessage. (/home/runner/node_modules/request/request.js:1083:12)

**Comment by barbeau** [comment]
@ibrahimozden Have you tried parsing the feed with another GTFS-rt client like the GTFS-rt validator to see if it parses correctly?

https://github.com/CUTR-at-USF/gtfs-realtime-validator

You'll need to provide more sample code of how you're parsing the feed and example data for us to help more. These types of getting started requests are also best directed to the GTFS-realtime mailing list here - https://groups.google.com/forum/#!forum/gtfs-realtime. Could you post any additional info there?  Thanks!
