### ISSUE TITLE
Compiling different extensions

### ISSUE THREAD

**Issue by mhkeller** [MobilityData/gtfs-realtime-bindings#62]
How would you compile and use an extension file with this library. For example, here is the one one from New York City: http://datamine.mta.info/sites/all/files/pdfs/nyct-subway.proto.txt

**Comment by barbeau** [comment]
@mhkeller You'd replace the [`gtfs-realtime.proto`](https://github.com/MobilityData/gtfs-realtime-bindings/blob/master/gtfs-realtime.proto) file in the root of this project with the .proto file for the extension (keeping the `gtfs-realtime.proto` name, unless you want to update the name in the subseequent steps), and then follow the UPDATING.MD steps for each language subfolder to re-generate the bindings code. For example, here's the Java [UPDATING.MD](https://github.com/MobilityData/gtfs-realtime-bindings/blob/master/java/UPDATING.md).

You'd then have a local version of the library on your machine you could use in your own applications.

Does that answer your question?

**Comment by mhkeller** [comment]
Yes I understand how to go through that process –  thanks for the quick reply. I'll be using nodejs so I'll [follow this](https://github.com/MobilityData/gtfs-realtime-bindings/blob/master/nodejs/UPDATING.md). 

One thing that confuses is me is I would have thought that the nyct-subway.proto file is something that would be loaded in addition to the gtfs-realtime.proto file since it seems like it extends that format. But what I understand what you're saying is that this represents the full spec?

Looking at the file I linked, it begins with

```
option java_package = "com.google.transit.realtime"; 

import "gtfs-realtime.proto";
```

Which seems to me like it's looking for the `gtfs-realtime.proto` file in the same directory. Maybe I should rename `gtfs-realtime.proto` to something like `base.proto` and then change the third line in my file to read `import "base.proto";`?

**Comment by barbeau** [comment]
@mhkeller Ah, sorry, I answered too quickly. Yes, I believe you're right. Best approach would be to keep the same filenames and just change UPDATING.MD instructions to process the extension file instead of `gtfs-realtime.proto`.

Please give that a shot and let me know if that works.

**Comment by mhkeller** [comment]
@barbeau success, many thanks! All I had to do was change the file name in `package.json` and npm link my local version. 

A clearer response before from me would have been "Yes that answers my question to understand how to through that process" since I would have been staring at it for quite a while to make sure I was doing it right! Feel free to close this. Thanks again!

**Comment by barbeau** [comment]
@mhkeller Glad that worked!
