### ISSUE TITLE
Error in the official Google Transit API Node.js sample

### ISSUE THREAD

**Issue by wmcb91** [MobilityData/gtfs-realtime-bindings#66]
In [the official Google Transit API Node.js sample](https://developers.google.com/transit/gtfs-realtime/examples/nodejs-sample) the code on line 11 will throw this error: `TypeError: Cannot read property 'decode' of undefined`.

```js
// Incorrect
var feed = GtfsRealtimeBindings.FeedMessage.decode(body);

// Corrected
var feed = GtfsRealtimeBindings.transit_realtime.FeedMessage.decode(body);

```

**Comment by barbeau** [comment]
@wmcb91 Thanks for reporting this! We'll try to get this fixed.

**Comment by barbeau** [comment]
@wmcb91 Looks like this is fixed here - https://developers.google.com/transit/gtfs-realtime/examples/nodejs-sample. Thanks for reporting!
