### ISSUE TITLE
protobuf-java version is really old

### ISSUE THREAD

**Issue by chadselph** [MobilityData/gtfs-realtime-bindings#75]
The java bindings are [pulling in](https://github.com/MobilityData/gtfs-realtime-bindings/blob/master/java/pom.xml#L54-L57) a protobuf-java library from July 2018 that logs a bunch of warnings on Java 9+ due to using unsafe APIs. This [has been fixed](https://github.com/protocolbuffers/protobuf/issues/3781) for a while now, so it would be nice to update to a [newer version](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java), maybe 3.14.0.

**Comment by barbeau** [comment]
👍  as long as the tests pass. PRs welcome! :)

**Comment by chadselph** [comment]
@barbeau see attached PR
