### ISSUE TITLE
Node.js examples for using gtfs-realtime-bindings.js

### ISSUE THREAD

**Issue by dancesWithCycles** [MobilityData/gtfs-realtime-bindings#77]
Hi folks,
I hope this finds you well. Thank you very much for your work on this awesome repository. I am looking for examples how to use the bindings in node.js. Especially, I am struggling with encoding messages. I would appreciate you pointing me to any usage example?
Btw, what is the reason using gtfs-realtime-bindings.js instead of protobuf.js? Is it just the convenience that I do not need to compile the javascript files anymore or is there more magic involved?

Cheers!

**Comment by jameslinjl** [comment]
@dancesWithCycles late response here, but the typical development workflow using protocol buffers is for a developer to use the protobuf compiler (protoc) along with a plugin (e.g. protobuf.js) to generate code that meets can serialize and deserialize data that complies with the schema (in the .proto file(s)). This process can be a bit annoying and tedious, especially for developers who have never worked with protobuf before, so these bindings are pre-compiled / generated for developers to skip that step and directly interact with GTFS real-time data in the supported languages.

Other than that, there isn't any more magic involved!

**Comment by isabelle-dr** [comment]
Closing this issue, the question has been answered. Thanks @jameslinjl !
