### ISSUE TITLE
Go: github.com/golang/protobuf is deprecated

### ISSUE THREAD

**Issue by MKuranowski** [MobilityData/gtfs-realtime-bindings#86]
The Go bindings rely on the github.com/golang/protobuf package, which [has been deprecated since March 2021](https://github.com/golang/protobuf/commit/ae97035608a719c7a1c1c41bed0ae0744bdb0c6f).

The bindings should probably be updated to use [google.golang.org/protobuf](https://pkg.go.dev/google.golang.org/protobuf) instead.

**Comment by jameslinjl** [comment]
@isabelle-dr this issue should be resolved now!

**Comment by isabelle-dr** [comment]
Indeed, thanks for the ping! Closing, resolved in #106
