### ISSUE TITLE
artefact org.mobilitydata:gtfs-realtime-bindings:0.0.8 is not present in maven central.

### ISSUE THREAD

**Issue by cspada** [MobilityData/gtfs-realtime-bindings#96]
The org.mobilitydata group is not even present.

**Comment by barbeau** [comment]
@cspada Thanks for opening this issue. Something went wrong in the PR that was supposed to publish to Maven Central and we need to investigate further:
https://github.com/MobilityData/gtfs-realtime-bindings/pull/92#issuecomment-1145454882

**Comment by maximearmstrong** [comment]
Fixed in #97. It is [here](https://s01.oss.sonatype.org/content/repositories/releases/org/mobilitydata/gtfs-realtime-bindings/0.0.8/).
