### ISSUE TITLE
any support for typescript types?

### ISSUE THREAD

**Issue by Joe-ChenZ** [MobilityData/gtfs-realtime-bindings#99]
It seems like i can't access the subfields of feed.entity. 

```
request(requestSettings, (error: any, response: { statusCode: number; }, body: any) => {
  if (!error && response.statusCode == 200) {
    var feed = GtfsRealtimeBindings.transit_realtime.FeedMessage.decode(body);
    feed.entity.forEach((entity: any) => {
      if (entity.TripUpdate) {
        console.log(entity.TripUpdate);
      }
    //   console.log(entity.trip_update);
    //   console.log(entity);
    
    });
  }
});
```

Apparently 
` if (entity.TripUpdate) ` never passes because entity is of type any, but it is of a specific realtime transit type, so i need to install it first. 

wouldn't work either when i do 
```
feed.entity.forEach((entity: { TripUpdate: any; }) => {
      if (entity.TripUpdate) {
        console.log(entity.TripUpdate);
      }
```
entity.TripUpdate is printed as undefined

**Comment by jameslinjl** [comment]
@Joe-ChenZ I think you may be running into issues because of the case of `entity.TripUpdate` vs `entity.tripUpdate` (https://github.com/MobilityData/gtfs-realtime-bindings/blob/master/nodejs/gtfs-realtime.js#L589-L595)

I was able to pull from the (NY) MTA's API with the following:
```
const GtfsRealtimeBindings = require("gtfs-realtime-bindings");
const https = require("https");

https
  .get(
    "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace",
    {
      headers: {
        "x-api-key": "<redacted>",
      },
    },
    (resp) => {
      const buffers = [];

      // A chunk of data has been received.
      resp.on("data", (chunk) => {
        buffers.push(chunk);
      });

      // The whole response has been received.
      resp.on("end", () => {
        const data = Buffer.concat(buffers);
        const feed =
          GtfsRealtimeBindings.transit_realtime.FeedMessage.decode(data);
        feed.entity.forEach(function (entity) {
          if (entity.tripUpdate) {
            console.log(JSON.stringify(entity.tripUpdate));
          }
        });
      });
    }
  )
  .on("error", (err) => {
    console.log("Error: " + err.message);
  });
```

**Comment by jameslinjl** [comment]
also, it should be pretty straight-forward to add TS types. i can help to do that soon once i (hopefully) get my first improvements for the JS bindings merged (https://github.com/MobilityData/gtfs-realtime-bindings/pull/103)

**Comment by gauthier-th** [comment]
I'm also interested in TS types and can also help

**Comment by jameslinjl** [comment]
@gauthier-th nice! i already have a local branch which adds the TS types, so will probably put that up once #103 is merged (the approach is fairly trivial, just using `pbts` to generate a `.d.ts` file and then specifying that file as `types` in the `package.json`. if you have feedback on that approach, please let me know!

perhaps something helpful here might be to help write a test / example(s) using TS?

**Comment by gauthier-th** [comment]
yep, i did the same on my side too.
sure! i could write this.

**Comment by jameslinjl** [comment]
https://github.com/MobilityData/gtfs-realtime-bindings/pull/105 is up now! @gauthier-th feel free to either propose changes onto that PR (or you can put up your own PR of tests / example(s) after this one is merged)

**Comment by gauthier-th** [comment]
I think we should already solve #104 and #105 before adding more documentation / examples for TS

**Comment by jameslinjl** [comment]
@isabelle-dr once you publish the newest node package version to NPM, you should be able to close this issue!

**Comment by sambencivengo** [comment]
@jameslinjl  Any idea when the latest package will be published to NPM?

**Comment by jameslinjl** [comment]
@sambencivengo - that's in MobilityData folks' hands - poke @isabelle-dr :)

**Comment by gauthier-th** [comment]
Hi @isabelle-dr ! Do you have any news on this?

**Comment by jameslinjl** [comment]
@gauthier-th I'll check in with Isabelle in the new year. I would expect much motion here until the holidays are behind us, since most stuff in North America comes to a standstill between Christmas and New Years.

**Comment by gauthier-th** [comment]
Any news here?

**Comment by jameslinjl** [comment]
@gauthier-th yeah, i chatted with isabelle. she's on vacation and then heading to a transportation conference over the next couple weeks. once she's back, she said she'll get all this published

**Comment by jameslinjl** [comment]
ETA 1/17

**Comment by gauthier-th** [comment]
Ok, thanks!

**Comment by jameslinjl** [comment]
@sambencivengo @gauthier-th NPM packages have been published! I have QA'ed `1.1.1` and it lgtm

**Comment by jameslinjl** [comment]
@isabelle-dr If we don't hear any complaints over a couple days, then we can close out this issue

**Comment by isabelle-dr** [comment]
Awesome, thanks for making this happen!
